/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyRequestsImport } from './routes/my-requests'
import { Route as CreateRequestImport } from './routes/create-request'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MyRequestsRoute = MyRequestsImport.update({
  path: '/my-requests',
  getParentRoute: () => rootRoute,
} as any)

const CreateRequestRoute = CreateRequestImport.update({
  path: '/create-request',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-request': {
      id: '/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof CreateRequestImport
      parentRoute: typeof rootRoute
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-request': typeof CreateRequestRoute
  '/my-requests': typeof MyRequestsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-request': typeof CreateRequestRoute
  '/my-requests': typeof MyRequestsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-request': typeof CreateRequestRoute
  '/my-requests': typeof MyRequestsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-request' | '/my-requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-request' | '/my-requests'
  id: '__root__' | '/' | '/create-request' | '/my-requests'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRequestRoute: typeof CreateRequestRoute
  MyRequestsRoute: typeof MyRequestsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRequestRoute: CreateRequestRoute,
  MyRequestsRoute: MyRequestsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-request",
        "/my-requests"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-request": {
      "filePath": "create-request.tsx"
    },
    "/my-requests": {
      "filePath": "my-requests.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
